apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kuar-validator
webhooks:
  - name: validator.kuar.com
    rules:
    - apiGroups:
      - "beta.kuar.com"
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - loadtests
    clientConfig:
      url: #TODO
      caBundle: #TODO
